--- #YAML:1.0
name                        : Test-Database
version                     : 0.02
abstract                    : Create a database for various drivers
author:              
  - Philippe Bruhat
  - Greg Sabino Mullane <greg@endpoint.com>
  - Mark Johnson <mark@endpoint.com>
  - Selena Deckelmann <selenta@endpoint.com>
  - Josh Tolly <josh@turnstep.com>

license                     : perl
distribution_type           : module
dynamic_config              : 1

requires:
  DBI                       : 1.52
  perl                      : 5.006001
  File::Spec                : 0
  File::Temp                : 0
  version                   : 0
build_requires:
  DBI                       : 1.52
  Test::More                : 0.61
  version                   : 0
configure_requires:
  DBI                       : 1.52
  version                   : 0
recommends:
  Perl::Critic              : 0
  Pod::Spell                : 0
  Test::Pod                 : 0.95
  Test::Pod::Coverage       : 0
  Test::Warn                : 0.08
  Test::YAML::Meta          : 0.03
  Text::SpellChecker        : 0

provides:
  Test::Database:
    file                    : Database.pm
    version                 : 0.02

keywords:
  - DBI
  - testing
  - database

resources:
  homepage                  : http://search.cpan.org/dist/Test-Database/
  license                   : http://dev.perl.org/licenses/
  bugtracker                : http://rt.cpan.org/Public/Dist/Display.html?Name=Test-Database
  MailingList               : http://www.nntp.perl.org/group/perl.dbd.pg/
  Repository                : http://bucardo.org/Test-Database.git

meta-spec:
  version                   : 1.4
  url                       : http://module-build.sourceforge.net/META-spec-v1.4.html

generated_by                : emacs
